portfolio/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("resume.urls", namespace="resume")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

resume/urls.py
from django.urls import path
from . import views

app_name = "resume"
urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("projects/", views.projects, name="projects"),
    path("experience/", views.experience, name="experience"),
    path("certificates/", views.certificates, name="certificates"),
    path("contact/", views.contact, name="contact"),
    path("resume/", views.resume, name="resume"),
    path("aboutproject<int:project_id>/", views.aboutproject, name="aboutproject"),
]

resume/models.py
from django.db import models

# Create your models here.


class HomeInfo(models.Model):
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = "Home Info"

    def __str__(self):
        return self.title


class About(models.Model):
    about = models.TextField(blank=True)

    class Meta:
        verbose_name_plural = "About"

    def __str__(self):
        return self.about


class Projects(models.Model):
    title = models.CharField(max_length=100)
    decription = models.TextField(blank=True)
    project_photo = models.ImageField(upload_to="images/projects_img")
    project_link = models.URLField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Projects"


class Experience(models.Model):
    Company = models.CharField(max_length=100, blank=True, default="ok")
    Position = models.CharField(max_length=100, blank=True, default="ok")
    Duration = models.CharField(max_length=100, blank=True, default="ok")

    def __str__(self):
        return self.Company

    class Meta:
        verbose_name_plural = "Experience"


class Certificates(models.Model):
    title = models.CharField(max_length=100)
    certificate_id = models.CharField(max_length=25, blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Certificates"

resume/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.contrib.staticfiles.storage import staticfiles_storage

from resume.models import About, HomeInfo, Projects, Experience, Certificates
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def home(request):
    info = HomeInfo.objects.all()
    return render(request, "home.html", {"info": info, "is_homepage": True})


def about(request):
    items = About.objects.all()
    return render(request, "about.html", {"items": items})


def projects(request):
    project_show = Projects.objects.all()
    paginator = Paginator(project_show, 1)
    page = request.GET.get("page")
    print(page)
    try:
        project_show = paginator.page(page)
    except PageNotAnInteger:
        project_show = paginator.page(1)
    except EmptyPage:
        project_show = paginator.page(paginator.num_pages)
        print(project_show)

    return render(
        request, "projects.html", {"project_show": project_show, "page": page}
    )


def aboutproject(request, project_id):
    project = get_object_or_404(Projects, id=project_id)
    print(project.title, project.decription)
    return render(request, "aboutproject.html", {"project": project})


def experience(request):
    experience = Experience.objects.all()
    return render(request, "experience.html", {"experience": experience})


def certificates(request):
    show_cert = Certificates.objects.all()
    return render(request, "certificates.html", {"show_cert": show_cert})


def contact(request):
    return render(request, "contact.html")


def resume(request):
    resume_path = "cv/python.pdf"
    resume_path = staticfiles_storage.path(resume_path)
    if staticfiles_storage.exists(resume_path):
        with open(resume_path, "rb") as resume_file:
            response = HttpResponse(resume_file.read(), content_type="application/pdf")
            response["Content-Disposition"] = 'attachment; filename="python.pdf"'
            return response
    else:
        return HttpResponse("Resume not found", status=404)

resume/templates/about.html
{% extends 'base.html' %} {% load static %} <br />
{% block content1 %}
<div class="row my-5">
  <div class="col-4 d-flex justify-content-center align-items-center">
    <div class="circular-image-container">
      <img
        class="circular-image"
        src="{% static 'images/cheche.jpeg' %}"
        alt="image"
      />
    </div>
  </div>
  <!-- About -->
  {% if items %} {% for item in items %}
  <div class="col-7 text-left text-light">{{ item.about|safe }}</div>
  {% endfor %} {% else %}
  <p>No About</p>
  {% endif %}

  <!-- Tech Stack -->
  <style>
    .progress-bar {
      height: 20px; /* Adjust the height here */
    }
  </style>

  <div class="container mt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="text-center" style="color: #4fffb0">Tech Stack</h2>
        <div class="col-12 mt-4">
          <div class="tech-bar text-light">
            <span>Html5</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 90%; background-color: #4fffb0"
              >
                90%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Fastapi</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 90%; background-color: #4fffb0"
              >
                90%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>CSS3</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 85%; background-color: #06b6d4"
              >
                85%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>JavaScript</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 75%; background-color: #ffca28"
              >
                60%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Python</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 80%; background-color: #3572a5"
              >
                80%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Dart</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 70%; background-color: #0175c2"
              >
                70%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Linux</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 60%; background-color: #333333"
              >
                60%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Django</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 90%; background-color: #092e20"
              >
                90%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Bootstrap</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 85%; background-color: #563d7c"
              >
                85%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>DRF</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 70%; background-color: #4e8e4a"
              >
                70%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Networking</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 60%; background-color: #007bff"
              >
                60%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>Markdown</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 65%; background-color: #4a4a4a"
              >
                65%
              </div>
            </div>
          </div>

          <div class="tech-bar text-light">
            <span>WordPress</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 55%; background-color: #21759b"
              >
                55%
              </div>
            </div>
          </div>

          <!-- <div class="tech-bar text-light">
            <span>Docker</span>
            <div class="progress">
              <div
                class="progress-bar"
                style="width: 30%; background-color: #2496ed"
              >
                70%
              </div>
            </div>
          </div>-->
        </div>
      </div>
    </div>
  </div>

  {% endblock content1 %}

  <style>
    .tech-bar {
      margin-bottom: 1rem;
    }

    .progress {
      height: 25px;
      background-color: #f1f1f1;
      border-radius: 20px;
      overflow: hidden;
    }

    .progress-bar {
      height: 50%;
      width: 50%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: white;
      font-weight: bold;
      border-radius: 20px;
    }

    .circular-image {
      border-radius: 50%;
      width: 100%;
      height: auto;
      box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
    }

    .circular-image-container {
      border-radius: 50%;
      overflow: hidden;
      width: 150px;
      height: 150px;
      background: linear-gradient(135deg, #06b6d4, #4fffb0);
      padding: 5px;
      box-shadow: 0 8px 16px rgba(0, 0, 0, 0.3);
    }

    h2 {
      font-size: 2rem;
      margin-bottom: 1rem;
    }
    .container {
      width: 40%;
    }
  </style>
</div>

resume/templates/aboutproject.html
{% if project %}

<div>
    <h1>{{ project.title }}</h1>
     <img
      src="{{ project.project_photo.url }}"
      width="500"
      height="500"
      class="img-fluid"
      alt="projects"
    />
    <h4>{{ project.decription|safe }}</h4>
    <a href="{% url 'resume:home' %}">Back</a>
</div>
{% endif %}

<style>
    div {
      
        text-align: center;
    }
    
</style>

resume/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% block title %} Portfolio {% endblock title %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    {% comment %}
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
      rel="stylesheet"
    />
    {% endcomment %} {% comment %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    {% endcomment %}
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
    />
  </head>
  <body>
    {% include "navbar.html" %} {% if is_homepage %}
    <div class="container mt-5">
      <div class="row justify-content-center">
        <div class="col-md-6 col-12 text-center">
          <div class="splash">
            <h1 class="fade-in">
              <div
                style="
                  width: 100px;
                  height: 100px;
                  border-radius: 50%;
                  overflow: hidden;
                  margin: 0 auto;
                "
              >
                <img
                  class="circular-image"
                  src="{% static 'images/cheche.jpeg' %}"
                  style="width: 100%; height: 100%; object-fit: cover"
                  alt="circular-image"
                />
              </div>
              <br />
              Welcome To My Portfolio
            </h1>
          </div>
        </div>
      </div>
    </div>

    {% endif %}
    <div class="container">{% block content1 %} {% endblock content1 %}</div>

    {% include "footer.html" %}

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>

    <script src="{% static 'js/app.js' %}"></script>
  </body>
</html>

resume/templates/certificates.html
{% extends 'base.html' %}

{% block content1 %}
<br />

<div class="container mt-5">
    <div class="row">
        {% for certificate in show_cert %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ certificate.title }}</h5>
                    <p class="card-text">Certificate ID: {{ certificate.certificate_id }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock content1 %}

resume/templates/contact.html
{% extends 'base.html' %} <br />
{% load static %} <br />
{% block content1 %}
<div class="row my-2 mx-5">
  <div class="col-4 text-center my-5 text-light">
    <h1 class="mt-5">Stay Connected</h1>
    <h3 class="mt-5">checheomenife@gmail.com</h3>
    <div class="d-flex justify-content-center align-items-center mt-5">
      <a href="https://linkedin.com">
        <img src="{% static 'images/linkedin.jpeg' %}" alt="linkedin"width"50"
        height="50" class="social_links ms-3" >
      </a>
      <a href="https://github.com">
        <img src="{% static 'images/github.png' %}" alt="github"width"45"
        height="50" class="social_links ms-3" >
      </a>
      <a href="https://discord.com">
        <img src="{% static 'images/discord.jpeg' %}" alt="discord"width"45"
        height="50" class="social_links ms-3" >
      </a>
    </div>
  </div>
  <!--  <div class="col-5 offset-1 mt-3 pull-right">  -->
  <div class="col-md-6 offset-1 mt-3 pull-right">
    <div class="container form-container">
      <form
        action="https://formspree.io/f/mknlgndv"
        method="POST"
        onsubmit="return submitForm(event)"
      >
        {% csrf_token %}
        <div class="form-group m-3">
          <label for="name">Name</label>
          <input
            type="name"
            class="form-control"
            id="name"
            aria-describedby="namehelp"
            required
            placeholder="Enter name"
          />
        </div>
        <div class="form-group m-3">
          <label for="email">Email</label>
          <input
            type="email"
            class="form-control"
            id="email"
            aria-describedby="emailhelp"
            placeholder="Enter email"
          />
        </div>

        <div class="form-group m-3">
          <label for="tel">Tel</label>
          <input
            type="tel"
            class="form-control"
            id="tel"
            aria-describedby="telhelp"
            required
            placeholder="Enter telephone number"
            pattern="[0-9]{10,15}"
            title="Please enter a valid phone number (10 to 15 digits)"
          />
          <small id="telhelp" class="form-text text-muted">
            Enter a valid phone number.
          </small>
        </div>

        <div class="form-group m-3">
          <label for="msg">Message</label><br />
          <textarea
            name="msg"
            required
            type="message"
            id=""
            rows="2"
            id="msg"
            placeholder="Enter message"
          ></textarea>
        </div>

        <button type="submit" placeholder class="btn btn-primary">
          Submit
        </button>
      </form>
      <div id="success-message" style="display: none"></div>
    </div>
  </div>
</div>

{% endblock content1 %}

resume/templates/experience.html
{% extends 'base.html' %} <br />
{% load static %} <br />
{% block content1 %}

<div class="container mt-5">
    <div class="row">
        {% for exp in experience %}
        <div class="col-md-4">
            <div class="card mb-4 shadow-sm">
                <div class="card-body">
                    <h5 class="card-title">{{ exp.Company }}</h5>
                    <p class="card-text">Position: {{ exp.Position }}</p>
                    <p class="card-text">Duration: {{ exp.Duration }}</p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
 {% comment %} <div class="row my-2"> {% endcomment %}
  {% comment %} {% for experience in experience %} {% endcomment %}

  {% comment %} <div class="jumbotron jumbotron-fluid col-3 mt-2 mx-3">
   
   <h1 class="display4">{{ experience.Company }}</h1>
    <p class="lead">{{ experience.Position }}</p>
    <p class="lead">{{ experience.Duration }}</p>
  </div> {% endcomment %}

  {% comment %} {% endfor %} {% endcomment %}
{% comment %} </div>  {% endcomment %}



{% endblock content1 %}

resume/templates/footer.html
<footer class="mt-5 text-center text-light">
  <button style="font-size: 24px" class="btn btn-outline-light btn-sm mb-3">
    <a
      href="https://wa.me/+2347048167337"
      style="color: inherit; text-decoration: none"
    >
      <i class="fab fa-whatsapp"></i>
    </a>
  </button>

  <p class="text-center">Copyright &copy; 2022 Cheche. All rights reserved.</p>

  <small>Powered by Django</small>
</footer>

resume/templates/home.html
{% extends 'base.html' %} {% load static %} {% block content1 %} <br />

<div class="row my-5">
  <div class="col-12 d-flex justify-content-center align-items-center">
    <div class="circular-image-container">
      <img
        class="circular-image"
        src="{% static 'images/cheche.jpeg' %}"
        alt="image"
      />
    </div>
  </div>
</div>

{% for item in info %}
<div class="col-12 mt-3 text-center">
  <h4 class="title">{{ item.title|safe }}</h4>
  <div class="name">
    <h1>{{ item.name|safe }}</h1>
    <h3>{{ item.position|safe }}</h3>
    {% endfor %}
    
  </div>
  <div
    class="col-12 text-center d-flex justify-content-center align-items-center mt-3"
  >
    <div
      class="col-12 text-center d-flex justify-content-center align-items-center mt-3"
    >
      <a href="https://linkedin.com">
        <img src="{% static 'images/linkedin.jpeg' %}" alt="linkedin"width"50"
        height="50" class="social_links ms-3" >
      </a>
      <a href="https://github.com">
        <img src="{% static 'images/github.png' %}" alt="github"width"45"
        height="50" class="social_links ms-3" >
      </a>
      <a href="https://discord.com">
        <img src="{% static 'images/discord.jpeg' %}" alt="discord"width"50"
        height="50" class="social_links ms-3" >
      </a>
    </div>
  </div>
</div>
{% endblock content1 %}

resume/templates/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand ms-5 m-2" href="/">Cheche</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarText"
      aria-controls="navbarText"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link active"
            aria-current="page"
            href="{% url 'resume:home' %}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume:projects' %}">Projects</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume:experience' %}"
            >Experience</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume:certificates' %}"
            >Certificates</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume:contact' %}">Contact</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'resume:resume' %}">Resume</a>
        </li>
      </ul>
      <i id="icon" class="fas fa-moon"></i>
    </div>
  </div>
</nav>

<style>
  .active {
    background-color: black;
  }
</style>

resume/templates/pagination.html
<!-- resume\templates\pagination.html -->
{% load static %}
 <link rel="stylesheet" href="{% static 'css/style.css' %}">


   <!-- Pagination -->
<div class="pagination">
    <span class="">
        {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}" class="page-link">Previous</a>
        {% endif %}
    </span>

    <span class="">
        Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    <span class="">
        {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}" class="page-link">Next</a>
        {% endif %}
    </span>
</div>

resume/templates/projects.html
{% extends 'base.html' %} <br />
{% load static %} <br />
{% block content1 %}
<div class="row my-2">
  {% for project in project_show %}
  <div class="col-4">
    <h4 style="color: #fff">{{ project.title|safe }}</h4>
    <img
      src="{{ project.project_photo.url }}"
      width="500"
      height="800"
      class="img-fluid"
      alt="projects"
    />
    {% comment %}
    <h4 style="color: #fff" class="mt-3">{{ project.decription|safe }}</h4>
    {% endcomment %}

    <button class="btn btn-outline-light mt-3">
      <a href="{{ project.project_link }}" style="text-decoration: none"
        >View Project</a
      >
    </button>
    <a
      href="{% url 'resume:aboutproject' project.id  %}"
      class="btn btn-outline-light mt-3 mx-3"
      >More</a
    >
  </div>
  {% endfor %}
</div>

<br />
<!-- Pagination-->
{% include 'pagination.html' with page=project_show %}
<!--End Pagination-->

{% endblock content1 %}